[workspace]
members = [
    "crypto-openssl-sys",
    "identity",
    "identity-types",
    "protocol",
    "vision",
    "vision-opencv-sys",
    "templates",
    "daemon",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.85"
license = "GPL-3.0-or-later"

[workspace.dependencies]
zeroize = { version = "1.8", features = ["derive"] }

[workspace.lints.rust]
unsafe_code = "forbid"

[workspace.lints.clippy]
all = "deny"
pedantic = "deny"
