[package]
name = "kfaceauth-templates"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
autobins = false

[dependencies]
kfaceauth-crypto-openssl-sys = { path = "../crypto-openssl-sys" }
kfaceauth-identity-types = { path = "../identity-types" }
zeroize.workspace = true

[[bin]]
name = "kfaceauth-sync-vault"
path = "src/bin/kfaceauth-sync-vault.rs"

[[bin]]
name = "kfaceauth-policy"
path = "src/bin/kfaceauth-policy.rs"

[lints]
workspace = true
